{{- range .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: {{ .replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .image }}"
          ports:
            - containerPort: {{ .port }}
          env:
            {{- range .env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: microapp-secrets
                  key: JWT_SECRET
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .port }}
            initialDelaySeconds: 5
            periodSeconds: 5
{{- end }}
